theme: jekyll-theme-midnight

# Site settings
title: ruihan.tech
subtitle: ''
keywords:
author: Wu Ruihan
email: defbobo@sina.com
description: "ruihan personal sit."
baseurl: ""
#url: "https://liambob77.github.io"
language: en

include:
  - index.md
  - README.md
  - git.md

theme: jekyll-theme-midnight
