theme: jekyll-theme-cayman

# Site settings
title: ruihan.tech
email: karpathy@cs.stanford.edu
description: "ruihan personal sit."
baseurl: ""
url: "https://liambob77.github.io"

include:
  - index.md
  - README.md
  - git.md
