theme: jekyll-theme-midnight

# Site settings
title: ruihan.tech
email: defbobo@sina.com
description: "ruihan personal sit."
baseurl: ""
url: "https://liambob77.github.io"

include:
  - index.md
  - README.md
  - git.md

theme: jekyll-theme-midnight
