theme: jekyll-theme-cayman

# Site settings
title: ruihan.tech
email: karpathy@cs.stanford.edu
description: "ruihan personal sit."
baseurl: ""
url: "https://liambob77.github.io"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
