theme: jekyll-theme-slate

# Site settings
title: ruihan.tech
subtitle: ''
keywords:
author: Wu Ruihan
email: defbobo@sina.com
description: "ruihan personal sit."
baseurl: ""
language: en

url: "https://liambob77.github.io"

include:
  - index.md
  - README.md
  - git.md

# theme: jekyll-theme-midnight
