site_name: Rui's Blog
site_url: https://ruihan.tech/
theme:
    name: material
    custom_dir: overrides
    language: en
    features:
        - navigation.tabs
        - search.highlight
        - search.suggest
        - header.autohide
    font:
        code: Roboto Mono
    palette:
        accent: deep purple
        primary: light blue

    highlightjs: true
    titles_only: 'true'
    collapse_navigation: 'false'
    prev_next_buttons_location: 'both'
    hljs_languages:
        - yaml
        - rust
    icon:
        logo: logo
    favicon: images/favicon.ico
repo_url: https://github.com/liambob77/liambob77.github.io/
repo_name: liambob77.github.io
site_author: Liam_Bob
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.highlight:
        linenums: true
        linenums_style: pymdownx.inline
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - def_list
plugins:
    - search:
        separator: '[\s\-\.]+'
extra:
  generator: false
  social:
    - icon: fontawesome/brands/weixin
      name: Liam_Bob on weixin
      
copyright: "Copyright &copy; 2018 - 2021 Liam_Bob"
google_analytics:
  - G-GE9R8TL75Z
  - auto
