site_name: "Rui's website"
repo_name: liambob77.github.io
# repo_url: https://github.com/liambob77/liambob77.github.io/
site_url: https://ruihan.tech/
site_author: Liam_Bob

theme:
    name: material
    custom_dir: overrides
    language: en
    features:
        - navigation.tabs
        - search.highlight
        - search.suggest
        - header.autohide
    font:
        code: Roboto Mono
    palette:
        scheme: preference
        accent: purple
        primary: lime

    highlightjs: true
    titles_only: true
    collapse_navigation: false
    hljs_languages:
        - yaml
        - rust
    icon:
        logo: logo
    favicon: images/favicon.ico

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.highlight:
        linenums: true
        linenums_style: pymdownx.inline
    - smarty
    - toc:
        permalink: true
    - sane_lists
    - def_list
plugins:
    - search:
        separator: '[\s\-\.]+'
extra:
  generator: false
  social:
    - icon: fontawesome/brands/weixin
      name: Liam_Bob
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/defbobo
      
copyright: "Copyright &copy; 2018 - 2021 Liam_Bob"

google_analytics:
  - G-GE9R8TL75Z
  - auto
