site_name: Ruihan
theme: readthedocs
repo_url: https://github.com/liambob77/liambob77.github.io/
repo_name: liambob77.github.io
site_author: Wu Ruihan
nav:
- Introduction: 'index.md'
- xueersi: 'docs_cici/'
- works: 'docs_tech/'
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists

