site_name: Ruihan
theme:
    name: material
    language: zh
    features:
        - navigation.tabs
        - search.highlight
        - search.suggest
        - header.autohide
    font:
        code: Roboto Mono
    palette:
        accent: deep purple
        primary: light blue

    highlightjs: true
    titles_only: 'true'
    collapse_navigation: 'false'
    prev_next_buttons_location: 'both'
    hljs_languages:
        - yaml
        - rust
    icon:
        logo: logo
repo_url: https://github.com/liambob77/liambob77.github.io/
repo_name: liambob77.github.io
site_author: Liam_Bob
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
plugins:
    - search:
        separator: '[\s\-\.]+'
extra:
  generator: false
  social:
    - icon: fontawesome/brands/weixin
      name: Liam_Bob on weixin
      
copyright: "Copyright &copy; 2018 - 2020 Liam_Bob"
